// next.js
import { Instrument_Sans } from "next/font/google";

// global styles
import "../globals.css";

// components
import LandingHeader from "@/components/header/landing-header";
import Main from "@/components/main/main";

// react-hot-toast
import { Toaster } from "react-hot-toast";

// font
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function MarketingLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen box-border overflow-auto ${instrumentSans.className}`}
      >
          <LandingHeader />
          <Main>
            <Toaster
              position="bottom-center"
              toastOptions={{
                duration: 5000,
                style: { background: "#333333", color: "#FAFAFA" },
              }}
            />
            {children}
          </Main>
      </body>
    </html>
  );
}
