// next.js
import { Instrument_Sans } from "next/font/google";

// global styles
import "./globals.css";

// header component
import Header from "@/components/header/header";
// main content container component
import Main from "@/components/main/main";
import { Toaster } from "react-hot-toast";

// font
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`p-4 h-screen box-border overflow-hidden bg-neutral-light-grey ${instrumentSans.className}`}
      >
        <Header />
        <Main>
          <Toaster position="bottom-center" />
          {children}
        </Main>
      </body>
    </html>
  );
}
