// next.js
import { Instrument_Sans } from "next/font/google";

// global styles
import "./globals.css";

// header component
import Header from "@/components/header/header";
// main content container component
import Main from "@/components/main/main";

// font
const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

// metadata
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`p-8 h-screen box-border overflow-hidden bg-neutral-light-grey ${instrumentSans.className}`}
      >
        <Header />
        <Main>{children}</Main>
      </body>
    </html>
  );
}
