// next.js
import { Instrument_Sans } from "next/font/google";

// global styles
import "../globals.css";

// provider
import Provider from "./provider";

// components
import AuthHeader from "@/components/header/auth-header";

// react-hot-toast
import { Toaster } from "react-hot-toast";

// font
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen box-border overflow-auto ${instrumentSans.className}`}
      >
        <Provider>
          <div className="md:h-screen md:w-screen md:flex md:flex-col md:items-center md:justify-center bg-neutral-light-grey">
            <AuthHeader />
            <Toaster
              position="bottom-center"
              toastOptions={{
                duration: 5000,
                style: { background: "#333333", color: "#FAFAFA" },
              }}
            />
            <main className="bg-white md:rounded-xl">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
