// next.js
import { Instrument_Sans } from "next/font/google";
import Image from "next/image";

// global styles
import "../globals.css";

// provider
import Provider from "./provider";

// components
import DashboardHeader from "@/components/header/dashboard-header";

// react-hot-toast
import { Toaster } from "react-hot-toast";
import PhoneMockup from "@/components/phone-mockup/phone-mockup";


// font
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: "Devlinks App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen box-border overflow-auto ${instrumentSans.className}`}
      >
        <Provider>
          <DashboardHeader />
          <main className="box-border bg-neutral-light-grey p-4 pb-20 lg:flex lg:gap-5">
            <div className="hidden lg:flex w-5/12 items-center justify-center bg-white rounded-xl">
              <PhoneMockup />
            </div>
            <div className="flex lg:w-7/12 lg:h-[810px] flex-col gap-10 bg-white rounded-xl pt-6 pb-4 md:pt-10">
              {children}
            </div>
          </main>
          <Toaster
            position="bottom-center"
            toastOptions={{
              duration: 5000,
              style: { background: "#333333", color: "#FAFAFA" },
            }}
          />
        </Provider>
      </body>
    </html>
  );
}
